config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :categories do
      resources :charges
    end
  end

  resources :user_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :User
  has_many :charges
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include CategoriesHelper

  before_filter :require_login

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end

  end

  def index
    @categories = current_user.categories.all
  end

  def show
    @passed_id = params[:user_id].to_i
    @current_user_id = current_user.id.to_i
    @category = Category.find(params[:id])
    @id_match = "not checked"

    if @passed_id == @current_user_id
      @id_match = "checked, they match"
      @charge = Charge.new
      @charge.category_id = @category_id

      i = 0
      avg = 0

      @category.charges.each do |charge|
        i = i + 1
        avg = avg + charge.amount
        @category.cat_average = avg / i
      end
    else
      @id_match = "checked, no match"
      redirect_to user_categories_path(@category.user_id)
    end
  end
  

  def new
    @user = current_user
    @category = current_user.categories.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = params[:user_id]

    @category.save

    redirect_to user_categories_path(@category)
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy
    redirect_to user_categories_path(@category.user_id)
  end


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include ChargesHelper

  before_filter :require_login

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end

  end

  def create
    @charge = Charge.new(charge_params)
    @charge.category_id = params[:category_id]
    @charge.date = Time.now

    @charge.save

    redirect_to user_category_path(@charge.category.user_id, @charge.category)
  end

  def destroy
    @charge = Charge.find(params[:id])
    @charge.destroy
    redirect_to user_category_path(@charge.category.user_id, @charge.category)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  include UserSessionsHelper

  def new
  end

  def create
    if login(params[:email], params[:password])
      @userid = current_user
      redirect_to user_categories_path(:user_id => @userid)
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_categories_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_params
    params.require(:category).permit(:cat_name, :cat_budget, :cat_average, :user_id)
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def charge_params
    params.require(:charge).permit(:merch, :amount, :desc, :id)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def usersessions_params
    params.require(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="top-bar">

  <div class="top-bar-left">
    <ul class="menu">
      <div class="menu-text">
        <strong>bdgtr</strong>
      </div>

      <li><%= link_to "Create a New Category", new_user_category_path %></li>
      </ul>
  </div>
  <%= render partial: 'layouts/user' %>
</div>
<hr>
<div class="row small-up-2 medium-up-4 large-up-6 align-spaced">

  <% @categories.each do |category| %>
  <%
  i = 0
  avg = 0
  category.charges.each do |charge|
    i = i + 1
    avg = avg + charge.amount
    category.cat_average = avg / i
  end
  %>

  <div class="column">
    <div class="card">
      <div class="card-divider">
        <h4><%= category.cat_name %></h4>
      </div>
      <div class="card-section">
        <p>Current average is <%= category.cat_average %></p>
        <p>Your budget is <%= category.cat_budget %></p>
        <%= link_to category.cat_name, user_category_path(category.user_id, category), class: 'button medium' %>
      </div>
    </div>
  </div>

  <% end %>

</div>

app/views/categories/new.html.erb
<div class="top-bar">

  <div class="top-bar-left">
    <ul class="menu">
      <div class="menu-text">
        <strong>Create a New Category</strong>
      </div>

      <li><%= link_to "back", user_categories_path %></li>
    </ul>
  </div>
  <%= render partial: 'layouts/user' %>
</div>

<%= form_for [ @user, @category ] do |f| %>
<div class="row small-up-1 medium-up-2 align-left">
  <div class="shrink columns">
    <%= f.label(:cat_name, 'Category Name') %><br />
    <%= f.text_field :cat_name %>
    <%= f.label(:cat_budget, 'Category Budget (daily)') %><br />
    <%= f.text_field :cat_budget %>
    <%= f.submit('Create Category', class: "button success")%>
  </div>
</div>
<% end %>

app/views/categories/show.html.erb
<div class="top-bar">

  <div class="top-bar-left">
    <ul class="menu">
      <div class="menu-text">
        <strong><%= @category.cat_name %></strong>
      </div>

      <li><%= link_to "back", user_categories_path %></li>
      <li><%= link_to "delete", user_category_path(@category.user_id, @category), class: "button alert hollow", method: :delete, data: {confirm: "Really delete the category?"} %></li>
    </ul>
  </div>
  <%= render partial: 'layouts/user' %>
</div>

<div class="row align-left">
  <div class="shrink columns">
    <h4>Current Average: <%= @category.cat_average %></h4>
  </div>
  <div class="shrink columns">
    <h4>Budget: <%= @category.cat_budget %></h4>
  </div>
</div>
<hr>
<div class="row small-up-1 medium-up-2 align-left">
  <div class="expand columns">
    <h4>New Charge:</h4>
    <div class="form">
      <%= form_for [current_user, @category, @charge ] do |f| %>
      <%= f.label :merch, "Merchant" %><br/>
      <%= f.text_field :merch %>
      <%= f.label :desc, "Description" %><br/>
      <%= f.text_area :desc %>
      <%= f.label :amount, "Amount" %><br/>
      <%= f.text_area :amount %>
      <%= f.submit('Save Charge', class: "button success")%>
      <% end %>
    </div>
  </div>
</div>
<hr>
<div class="row align-left">
  <div class="shrink columns">
    <h4>Charges:</h4>
  </div>
</div>

<div class="row">
  <div class="expand columns">
    <table class="table">
      <tr>
        <th>Date</th>
        <th>Amount</th>
        <th>Description</th>
        <th>Merchant</th>
        <th>Delete</th>
      </tr>

      <% @category.charges.reverse.each do |charge| %>
      <tr>
        <td><%= charge.date %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.desc %></td>
        <td><%= charge.merch %></td>
        <td><%= link_to "delete", user_category_charge_path(@category.user_id, @category.id, charge.id), method: :delete, data: {confirm: "Really delete the charge?"} %></td>
      </tr>
      <% end %>

    </table>
  </div>
</div>

app/views/layouts/_user.html.erb
<div class="top-bar-right">
  <ul class="menu">
    <% if logged_in? %>
    <li><%= "#{current_user.username}" %></li>
    <li><%= link_to "(logout)", logout_path %></li>
    <% else %>
    <li><%= link_to "(login)", login_path %></li>
    <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "bdgtr | Budget Tracking" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<div class="row">
  <div class="shrink columns">
    <h1>Login</h1>
  </div>
</div>

<div class="row">
  <div class="shrink columns">
    <%= form_tag user_sessions_path, method: :post do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
      <br/>
    </div>
    <div class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <br/>
    </div>
    <div class="actions">
      <%= submit_tag( "Login", class: "button" ) %>
    </div>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <div class="shrink columns">
<p>Don't have an account?</p>
<%= link_to "Register", new_user_path, class: "button hollow" %>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit(class: "button success") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
  <div class="columns">
<h1>New User</h1>

<%= render 'form' %>
<br>
<br>
<%= link_to 'Back', new_user_session_path, class: "button hollow" %>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>